version: '3.8'

services:
  neo4j:
    image: neo4j:latest
    container_name: knowledge-graph-neo4j
    ports:
      - "7475:7474" # HTTP (mapped to 7475 to avoid conflict)
      - "7688:7687" # Bolt (mapped to 7688 to avoid conflict)
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
      - neo4j-plugins:/plugins
    environment:
      NEO4J_AUTH: "neo4j/password"
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes" # Required for some GDS algorithms
      # Additional configuration for better performance
      NEO4J_dbms_memory_heap_initial__size: "512m"
      NEO4J_dbms_memory_heap_max__size: "2G"
      NEO4J_dbms_memory_pagecache_size: "1G"
      # Enable query logging for debugging
      NEO4J_dbms_logs_query_enabled: "INFO"
      NEO4J_dbms_logs_query_threshold: "0"
    networks:
      - knowledge-graph-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  neo4j-plugins:
    driver: local

networks:
  knowledge-graph-network:
    driver: bridge
    name: knowledge-graph-network
